<?php

namespace App\Http\Controllers\Admin;

use App\Actions\Charts\GenerateDailyChart;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Log;

class ChartController extends Controller
{
    public function index(): View
    {
        return view('admin.charts.index');
    }

    public function regenerate(Request $request, GenerateDailyChart $action): RedirectResponse
    {
        $validated = $request->validate([
            'date' => ['required', 'date', 'before_or_equal:today'],
        ]);

        $date = Carbon::parse($validated['date']);

        $chart = $action($date);

        Log::info('Chart manually regenerated by admin.', [
            'date' => $date->toDateString(),
            'admin_id' => $request->user()->id,
            'entries' => $chart->entries()->count(),
        ]);

        return redirect()->route('admin.charts.index')
            ->with('status', "Chart regenerated for {$date->toDateString()}.");
    }
}
